services:
    php: &php-service
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        env_file:
            - .env
        command: "php artisan serve --host=0.0.0.0 --port=8000"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend

    db:
        container_name: database
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ideasoft_case
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

volumes:
    postgres-data:
        driver: local

networks:
    backend:
        driver: bridge
